### ISSUE TITLE
run_computation.R refers to AUCINFOi/AUCINFPi as AUINFOi/AUINFPi in select circumstances

### ISSUE THREAD

**Issue by tensfeldt** [tensfeldt/openNCA#10]
in run_computation.R: the following code needs updating

1)     ```
if("MRTEVIFPi" %in% parameter_list && (!"AUCINFPi" %in% parameter_list || !"AUCTAUi" %in% parameter_list || !"AUMCTAUi" %in% parameter_list)){
      if(!"AUCINFPi" %in% parameter_list){
        parameter_list[[length(parameter_list)+1]] <- "**AUINFPi**"
      }
```

to 
   ```
 if("MRTEVIFPi" %in% parameter_list && (!"AUCINFPi" %in% parameter_list || !"AUCTAUi" %in% parameter_list || !"AUMCTAUi" %in% parameter_list)){
      if(!"AUCINFPi" %in% parameter_list){
        parameter_list[[length(parameter_list)+1]] <- "**AUCINFPi**"
      }
```

2)
   ```
 if("MRTEVIFOi" %in% parameter_list && (!"AUCINFOi" %in% parameter_list || !"AUCTAUi" %in% parameter_list || !"AUMCTAUi" %in% parameter_list)){
      if(!"AUCINFOi" %in% parameter_list){
        parameter_list[[length(parameter_list)+1]] <- "**AUINFOi**"
      }
```

to
    ```
if("MRTEVIFOi" %in% parameter_list && (!"AUCINFOi" %in% parameter_list || !"AUCTAUi" %in% parameter_list || !"AUMCTAUi" %in% parameter_list)){
      if(!"AUCINFOi" %in% parameter_list){
        parameter_list[[length(parameter_list)+1]] <- "**AUCINFOi**"
      }
```

**Comment by jhhughes256** [comment]
### Update

As of 6284702d62 three cases of **AUINFPi** and **AUINFOi** have been changed to **AUCINFPi** and **AUCINFOi** respectively. 

There are no other cases of **AUINFPi** or **AUINFOi** in `run_computation.R`, so I will close this issue.
