### ISSUE TITLE
2019-12-11 tc106 M1SD Computation error in auc_t1_t2 due to NA times in dataset

### ISSUE THREAD

**Issue by jhhughes256** [tensfeldt/openNCA#101]
### Error

When running tc106 M1SD the following error occurs while using actual time.

```
 Error in value[[3L]](cond) : 
  Error in auc_t1_t2(conc = tmp_df[, map_data$CONC], time = na.omit(tmp_df[, : Error in auc_t1_t2: 'time' is not a numeric vector
For SDEID 2300679002 
7. stop(paste0(e, "For SDEID ", unique(data_data[, map_data$SDEID])[i])) at run_M1_SD_computation.R#1881
6. value[[3L]](cond) 
5. tryCatchOne(expr, names, parentenv, handlers[[1L]]) 
4. tryCatchList(expr, classes, parentenv, handlers) 
3. tryCatch({
    tmp_df <- data_data[data_data[, map_data$SDEID] == unique(data_data[, 
        map_data$SDEID])[i], ]
    tmp_df <- tmp_df[order(tmp_df[, map_data$TIME]), ] ... at run_M1_SD_computation.R#831
2. run_M1_SD_computation(data = merged_data, map = map_data, method = method, 
    model_regex = model_regex, parameter_list = parameter_list, 
    return_list = return_list) at run_computation.R#2348
1. run_computation(data = d, map = mct, flag = flags, parameterset = parameterset) 
```

The SDEID which this error occurs for has the following following data. Notice that there is an NA time is PKATPD_ORIG and not PKPTMS. @tensfeldt is it likely that there will be NA times in datasets used by the comp engine? When removing the SDEIDs with these NA times the computation engine runs successfully.

```
> table(d[d$SDEID == 2300679002, "PKATPD_ORIG"], useNA = "always")

   0    1    2    3    4    6    8    9 <NA> 
   1    1    1    1    1    1    1    1    1 
```

When looking at the input to `auc_t1_t2` for this SDEID it can be seen that `time` enters the function with class omit, probably after going through an `na.omit` function. As a result it is not recognised by `is.vector` causing an error. 

```
> debug(auc_t1_t2)
> d <- d[d$SDEID == 2300679002,]
> flags <- flags[flags$PKDATAROWID %in% d$PKDATAROWID,]
> results_list <- run_computation(data = d, map = mct, flag = flags, 
  parameterset = parameterset)
debugging in: auc_t1_t2(conc = tmp_df[, map_data$CONC], time = na.omit(tmp_df[, 
    map_data$TIME]), t1 = tmp_df[, map_data$TIME][1], t2 = tmp_df[, 
    map_data$TIME][t], method = method, exflag = auc_flag, t_max = t_max)
Browse[2]> time
[1] 0 1 2 3 4 6 8 9
attr(,"na.action")
[1] 9
attr(,"class")
[1] "omit"
Warning messages:
1: In validate_timeconc_data(map, data, verbose = verbose) :
  No tau information provided in 'map'.
2: In validate_timeconc_data(map, data, verbose = verbose) :
  No told information provided in 'map'.
3: In run_M1_SD_computation(data = merged_data, map = map_data, method = method,  :
  Flag 'FLGACCEPTTAU' cannot be computed if 'TAUi' is not provided
4: In run_M1_SD_computation(data = merged_data, map = map_data, method = method,  :
  Flag 'FLGEMESIS' is not present in the dataset
5: In min(tmp[tmp$conc == c_min, ]$time, na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
Browse[2]> is.numeric(time) && is.vector(time)
[1] FALSE
```

Edit: Originally I thought this occurred for both actual and nominal time, however didn't realise that `flags$FLGTIME` was set to "ACTUAL".

**Comment by tensfeldt** [comment]
@jhhughes256 yes it is possible that TIME values with NAs will be present in the dataset for a variety of reasons, particularly for ACTUAL TIMES.

**Comment by tensfeldt** [comment]
@jhhughes256  Occurs with tc107. Here we have 2 records with d[,mct$ACTTIME] values == NA. In this particular case, flags$FLGTIME for those records are set to "NOMINAL" so that mechanism doesn't appear to work either. If the switching to nominal worked, the the NA values would be set to the nominal values for these 2 records and the TIME variable would have no NA values. That said, the presence of the NA values should NOT cause this failure even if it wasn't being switched so there are two issues here that need to be addressed. Setting to high priority.

**Comment by tensfeldt** [comment]
@jhhughes256  @rudraya this also occurs with tc108. Datasets for test cases tc107 and tc108 have been loaded to the sharepoint site.

**Comment by jhhughes256** [comment]
As of 00cdcd3 Computation error no longer occurs, however there may still be issues with how FLGTIME is handled when it includes both NOMINAL and ACTUAL time. Once I open a new issue to describe this behaviour I will close this one.

**Comment by jhhughes256** [comment]
Confirming that FLGTIME is handled correctly when it includes both NOMINAL and ACTUAL time. Closing issue.
