### ISSUE TITLE
2019-12-18 CENDINF, TENDINF return NA when there are no data records at the end of the infusion

### ISSUE THREAD

**Issue by jhhughes256** [tensfeldt/openNCA#121]
### Issue

When requesting CENDINF or TENDINF with a dataset that has no concentration data at the end of the infusion an NA is returned. As a result CENDINFDN also returns an NA.

Currently the logic used for CENDINF and TENDINF is to find the concentration or time in the dataset that corresponds with the first time plus the duration of infusion (`time[1] + dof`). This is also the wording in the computation engine specification up until now. The code that describes this logic from `cendinf.R` (lines 118-128) is provided below.

```r
  tmp <- data.frame(time, conc)  # create dataset
  c_endinf <- NA  # create placeholder value for output
  if(!is.na(dof)){  # ensure dof has a valid value
    tmp_end_dof <- tmp$time[1] + dof  # time at the end of the infusion
    if(tmp_end_dof %in% tmp$time){  # try to find a time in the data that matches the time at the end of the infusion
      c_endinf <- tmp[tmp$time == tmp_end_dof,]$conc[1]  # if there is a match update the value
    }
  } 
  return(c_endinf)  # return CENDINF
```

Blood samples may not always be taken at the exact time that the infusion ends. This can occur if there is no nominal sample at that time or if the actual time of the sample being slightly different (i.e. just before, just after).

There will be a change to the specification document to describe how to handle cases where there is no data record at the end of the infusion. This issue will be changed to include the new desired behaviour once the updated specification is uploaded.

**Comment by tensfeldt** [comment]
Refer to #122 and the Computation Engine Specifications Document in the man directory of the master branch.

CENDINF is the observed concentration at the time of the end of the infusion. If there is no observed concentration identified at time of the end of the infusion, the CENDINF is imputed as the CMAX value.

TENDINFis the time of the CENDINF at the end of the infusion. If there is no observed concentration identified at the time of the end of the infusion, the TENDINF is imputed as the TMAX value.

**Comment by jhhughes256** [comment]
This issue has been addressed as of 73826ef0b1. Output from tc103 M3SS showing the difference between the previous behaviour (824be9d6b9) versus current behaviour shown below.

```r
> head(r_old[, 1:16])
      SDEID DOSE   DOSEC  DOSEC1 DOF1 CENDINF1 CENDINFDN1 TENDINF1  CMAX CMAX1   CMAXDN  CMAXDN1 FLGACCEPTPREDOSE CMIN CMIN1 CMINDN
1  49420991  100 1.0e+08 1.0e+08 1.00       NA         NA       NA 30900 30900 309.0000 309.0000                1    0     0      0
2 157748714   50 5.0e+07 5.0e+07 1.00     5430     0.1086        1  6550  6550 131.0000 131.0000                1    0     0      0
3 216997173   15 1.5e+07 1.5e+07 1.00       NA         NA       NA  3640  3640 242.6667 242.6667                1    0     0      0
4 281691464  200 2.0e+08 2.0e+08 1.02       NA         NA       NA 69300 69300 346.5000 346.5000                1    0     0      0
5 293032605  200 2.0e+08 2.0e+08 1.02       NA         NA       NA 33400 33400 167.0000 167.0000                1    0     0      0
6 300251841   50 5.0e+07 5.0e+07 1.00    18100     0.3620        1 18100 18100 362.0000 362.0000                1    0     0      0
> head(r_new[, 1:16])
      SDEID DOSE   DOSEC  DOSEC1 DOF1 CENDINF1 TENDINF1  CMAX CMAX1   CMAXDN  CMAXDN1 FLGACCEPTPREDOSE CMIN CMIN1 CMINDN CMINDN1
1  49420991  100 1.0e+08 1.0e+08 1.00    30900 1.500000 30900 30900 309.0000 309.0000                1    0     0      0       0
2 157748714   50 5.0e+07 5.0e+07 1.00     5430 1.000000  6550  6550 131.0000 131.0000                1    0     0      0       0
3 216997173   15 1.5e+07 1.5e+07 1.00     3640 1.500000  3640  3640 242.6667 242.6667                1    0     0      0       0
4 281691464  200 2.0e+08 2.0e+08 1.02    69300 1.016667 69300 69300 346.5000 346.5000                1    0     0      0       0
5 293032605  200 2.0e+08 2.0e+08 1.02    33400 1.033333 33400 33400 167.0000 167.0000                1    0     0      0       0
6 300251841   50 5.0e+07 5.0e+07 1.00    18100 1.000000 18100 18100 362.0000 362.0000                1    0     0      0       0
```

**Comment by rudraya** [comment]
This issue seems to be resolved, the reason "CENDINFDNi" is not being generated because of it not present in the MCT. Please updated MCT for tc103 and add parameter "CENDINFDNi" to the PARAMETERLIST.

**Comment by jhhughes256** [comment]
When changing `mct$PARAMETERLIST` for tc103 M3SS so that it includes CENDINFDNi this variable is generated correctly in the output as per below. 

```r
> r
      SDEID DOSE   DOSEC  DOSEC1 DOF1 CENDINF1 CENDINFDN1 TENDINF1  CMAX CMAX1   CMAXDN  CMAXDN1 FLGACCEPTPREDOSE CMIN CMIN1 CMINDN
1  49420991  100 1.0e+08 1.0e+08 1.00    30900   309.0000 1.500000 30900 30900 309.0000 309.0000                1    0     0      0
2 157748714   50 5.0e+07 5.0e+07 1.00     5430   108.6000 1.000000  6550  6550 131.0000 131.0000                1    0     0      0
3 216997173   15 1.5e+07 1.5e+07 1.00     3640   242.6667 1.500000  3640  3640 242.6667 242.6667                1    0     0      0
4 281691464  200 2.0e+08 2.0e+08 1.02    69300   346.5000 1.016667 69300 69300 346.5000 346.5000                1    0     0      0
```
