### ISSUE TITLE
2019-11-15 tc010 execution, no optimization, no interpolation/extrapolation for partial AUCs, not complete at 15 minutes

### ISSUE THREAD

**Issue by tensfeldt** [tensfeldt/openNCA#14]
Reproducible, execution running for > 20 minutes
restarts of environment indicate that this is a code issue and not environmental. #

**Comment by jhhughes256** [comment]
### Update

I could replicate this issue in ae10cfa1d9. As of 9d8c936843 this now runs successfully with and without OPTIMIZEKEL. Issue can no longer be replicated so I will close it, feel free to reopen if it still occurs for you @tensfeldt .
