### ISSUE TITLE
2020-01-14 tc128 M1SD results in execution failure

### ISSUE THREAD

**Issue by tensfeldt** [tensfeldt/openNCA#155]
tc128 M1SD causes a crash

parameterset == "PARAMETERLIST"
mct$TIME == "ACTUAL" (switch to NOMINAL and flags$FLGTIME=="NOMINAL" still crashes)
mct$OPTIMIZEKEL == 1 (switch to 0 still crashes)

files for test case submitted to onedrive

```r
> results_list <- run_computation(data=d, map=mct, flag=flags, parameterset=parameterset)
Error in 1:(auc_len + 1) : result would be too long a vector
In addition: Warning messages:
1: In validate_timeconc_data(map, data, flag, verbose = verbose) :
  No tau information provided in 'map'.
2: In validate_timeconc_data(map, data, flag, verbose = verbose) :
  No told information provided in 'map'.
3: In run_computation(data = d, map = mct, flag = flags, parameterset = parameterset) :
  'TAUs and TOLDs values are not provided via 'flag'! Using values provided via 'data' instead!
4: In max(tapply(index1, index1, length)) :
 
 Show Traceback
 
 Rerun with Debug
 Error in 1:(auc_len + 1) : result would be too long a vector 
```

**Comment by rudraya** [comment]
This issue should be resolved as of b9858f9 and seems like it could have been fixed in a previous commit since I am not able to reproduce it on my side. Please let me know if it still occurs.

**Comment by jhhughes256** [comment]
I've tried to replicate this issue with commits dce4ed8 and cde2560, but am unable to get this execution failure. This issue cannot be replicated with commit b9858f9, however without being able to produce the original error I will leave closing this to @tensfeldt.

**Comment by tensfeldt** [comment]
Retested with commit a1fb2f9 and OPTIMIZEKEL==1. Parameters were generated but not in all cases as anticipated. That said, the specific issue to avoid the execution failure is cleared and this issue can be closed.
