### ISSUE TITLE
2019-11-17 tc010 IF FLGNOCMAX ==1 is incorporated in MCT, run_computation throws error

### ISSUE THREAD

**Issue by tensfeldt** [tensfeldt/openNCA#18]
If mct$FLGNOCMAX==1 (or FLGNOCMAX==0 it turns out) (i.e. prohibit CMAX from being incorporated into KEL selections through the optimizekel routine) the following error occurs with tc010:

```
> results_list <- run_computation(data=d, map=mct, flag=flags, parameterset=parameterset)
Error in value[[3L]](cond) : 
  Error in if (flg_no_cmax) {: missing value where TRUE/FALSE needed
For SDEID 2925168
In addition: Warning messages:
1: In run_M1_SD_computation(data = merged_data, map = map_data, method = method,  :
  Flag 'FLGACCEPTTAU' cannot be computed if 'TAUi' is not provided
2: In run_M1_SD_computation(data = merged_data, map = map_data, method = method,  :
 
 Show Traceback
 
 Rerun with Debug
 Error in value[[3L]](cond) : 
  Error in if (flg_no_cmax) {: missing value where TRUE/FALSE needed
For SDEID 2925168 
```
Not that if mct$OPTIMIZEKEL == 0 (i.e. do not optimize), this error doesn't occur even with mct$FLGNOCMAX==1.

Note that if mct$NOCMAX is included at all, the optimization routine fails with this error.

**Comment by jhhughes256** [comment]
### Update

This issue also occurs with tc012 (#22) tc013 (#25), tc015 and tc016.

**Comment by jhhughes256** [comment]
### Update

Running tc010 with OPTIMIZEKEL == 1 and FLGNOCMAX == 1 no longer causes an error. Also applies to error in tc012, tc013, tc015 and tc016. Output will undergo further testing, but this issue can be closed for now.
