### ISSUE TITLE
Fix error message: "Unable to find dosing interval for Stedy State data! Please provide a valid 'data' parameter"

### ISSUE THREAD

**Issue by tensfeldt** [tensfeldt/openNCA#184]
Seems like we could fix the following error message:

Unable to find dosing interval for **Stedy** State data! Please provide a valid 'data' parameter

to 

Unable to find dosing interval for **Steady** State data! Please provide a valid 'data' parameter

**Comment by jhhughes256** [comment]
This issue has been addressed in commit 626e458.
