### ISSUE TITLE
2020-02-20 negative time times should generate error messages and not compute parameters

### ISSUE THREAD

**Issue by tensfeldt** [tensfeldt/openNCA#194]
No specific test case at the moment but when encountering Negative Times Post Dose in the input time data, for profiles that have negative time post dose, a warning message should be generated that a negative time has been encountered and no parameters should be produced. Resulting Parameters should be reported in the output dataset as missing, i.e. NA.

**Comment by TomTensfeldt** [comment]
Retested with commit c49a1b4 with tc1580. Results are as expected. Issue can be closed.
