### ISSUE TITLE
2020-02-21 lasttime.R examples incorrect and lasttime() doesn't take into account BLQ/LLOQ values

### ISSUE THREAD

**Issue by tensfeldt** [tensfeldt/openNCA#195]
tc1510-M1SD-1 is used to test this issue.

**Comment by jhhughes256** [comment]
As #210 is now closed, I assume that this issue can also be closed. But I'm not sure what the original issue was, so going to have to leave it open.

**Comment by TomTensfeldt** [comment]
tc1510_M1SD-1 was tested with commit f5bfc3a. This test case was crafted to incorporate NA values as the PKCNCN values for the last 2 datapoints for 2 profiles. If these 2 datapoints are completely removed from the dataset, tc1510_M1SD-1 will execute and LASTTIME values are correct. 
Note however, the current execution will run but ONLY if these NA values are removed. If they are left in place in the original dataset, the execution fails to run. 

Note that #238 covers the issue that the computation engine fails with concentration values == NA.

This issue #195 can be closed on the basis that it is possible to generate results with data modification.
