### ISSUE TITLE
2020-04-02 tc1572 M4SS - CONC and CONCTIME, parameter outputs not provided in results from run_computation

### ISSUE THREAD

**Issue by TomTensfeldt** [tensfeldt/openNCA#202]
- datasets provided in onedrive repository
for M4SS executions, no CONC or CONCTIME outputs are provided.

**Comment by jhhughes256** [comment]
As of commit cca452d this issue no longer occurs. Output for tc1572 shown below.

```r
r[,c(grep("^SDEID$", names(r)), grep("^CON.+\\d+$", names(r)))]
       SDEID CONC1 CONCTIME1
1  661083556  9310         0
2  737250770  9230         0
3 1723871653  8280         0
4 2187657022  9970         0
5 2432717605  6170         0
6 3854759896  6450         0
```

**Comment by jhhughes256** [comment]
I've been informed that this is the opposite behaviour than intended, and that CONCi and CONCTIMEi were to be removed from the M4 methods. @TomTensfeldt please close this issue if I have misinterpreted your correspondence on this.

**Comment by jhhughes256** [comment]
As of commit 472a0a2 `CONC1` and `CONCTIME1` are no longer present in the computation engine output.

```r
r[,c(grep("^SDEID$", names(r)), grep("^CON", names(r)))]
       SDEID CONCU CONCNORMU
1  661083556 NG/ML        NA
2  737250770 NG/ML        NA
3 1723871653 NG/ML        NA
4 2187657022 NG/ML        NA
5 2432717605 NG/ML        NA
6 3854759896 NG/ML        NA
```
