### ISSUE TITLE
2020-04-04 tc1510 M1SS LASTTIME computed incorrectly

### ISSUE THREAD

**Issue by TomTensfeldt** [tensfeldt/openNCA#210]
Test case tc010 and tc1510

LASTTIME: Results of the comparison should be EQUAL, with all values identical, since this parameter is a specific time point from the conc-time dataset with no associated calculation.  However 4 of the 48 values are slightly different, for example: test 120; reference 120.067. In the parameter data (referencedata.csv, testdata.csv) none of the test values have any decimal places, while 4 of the reference values do. 

Refer to 2020-03-27_tc1510_M1SD.html

This is similar to #195

**Comment by jhhughes256** [comment]
Results from 2020-03-27_tc1510_M1SD.html

Add LASTTIME to refparams
```r
dft <- filter(df, !is.na(PKCNCN)) %>% select(SDEID, SUBJID, mct$CONC, timevar)
by_SDEID <- group_by(dft, SDEID)
b_result <- summarize(by_SDEID, LASTTIME=max(PKATPD))
refparams$LASTTIME <- b_result$LASTTIME
clist <- compare_parameters("LASTTIME$", alist=assessedparameters, ref.params=refparams, tst.params=results, tol=tolerance)
## testing LASTTIME vs LASTTIME 
## 4/48 mismatches (average diff: 0.0417)
## [23] 120 - 120 == -0.050
## [33] 120 - 120 == -0.067
## [37]  72 -  72 == -0.017
## [44] 120 - 120 == -0.033
if(length(clist$n.ref)>0 & length(clist$n.tst)>0) assessedparameters <- remove1(assessedparameters, clist$rname)
```

Referring to the latest commit with output from tc1510_M1SD_ed0aed3.html

Add LASTTIME to refparams
Selected TIME basis is Nominal with timevar=PKPTMS
```r
dft <- filter(df, !is.na(PKCNCN)) %>% select(SDEID, SUBJID, mct$CONC, timevar)
by_SDEID <- group_by(dft, SDEID) %>% rename(conc=mct$CONC, time=timevar)
b_result <- summarize(by_SDEID, LASTTIME=max(time))
refparams$LASTTIME <- b_result$LASTTIME
clist <- compare_parameters("LASTTIME$", alist=assessedparameters, ref.params=refparams, tst.params=results, tol=tolerance)
## testing LASTTIME vs LASTTIME 
## Equal
if(length(clist$n.ref)>0 & length(clist$n.tst)>0) assessedparameters <- remove1(assessedparameters, clist$rname)
```

This issue appears to no longer occur for tc1510.
