### ISSUE TITLE
2020-04-21 tc1511 M1SS AUCALL, AUCINFO and AUCINFP differences between test and reference larger than expected

### ISSUE THREAD

**Issue by TomTensfeldt** [tensfeldt/openNCA#211]
Testcases tc011 and tc1511

AUCALL, AUCINFO and AUCINFP: Differences between test and reference are larger than expected. The average difference of 0.263 is identical for all 3 parameters, suggesting a small but consistent difference between test and reference calculation methods. Compare to average differences in the range of 1013 to 10-15 for AUCTAU1, AUCTAU2 and AUCLAST (note, comparison for AUCLAST is the sum of test [AUCLAST1 + AUCLAST2} compared to reference AUCLAST). 

Refer to 2020-04-02_tc1511_M1SS.html

**Comment by jhhughes256** [comment]
I can't refer to any automated report from the 2nd of April, but I can confirm that automated reports from the latest commit f5bfc3a show no signs of differences between AUCALL, AUCINFO and AUCINFP.
