### ISSUE TITLE
2020-04-04 tc1511 M1SS AUMCINFO and AUMCINFP test values do not match reference. 

### ISSUE THREAD

**Issue by TomTensfeldt** [tensfeldt/openNCA#212]
tc011 and tc1511

AUMCINFO and AUMCINFP test values do not match reference. 

Refer to 2020-04-02_tc1511_M1SS.html

**Comment by jhhughes256** [comment]
I can't refer to any automated report from the 2nd of April, but I can confirm that automated reports from the latest commit f5bfc3a show no signs of differences between AUMCINFO and AUMCINFP.
