### ISSUE TITLE
2020-04-04 tc1515 M3SD VSSPW parameter does not match reference value. 

### ISSUE THREAD

**Issue by TomTensfeldt** [tensfeldt/openNCA#218]
VSSPW Parameter: Does not match. Calculation and unit conversion for the reference values in the qualification test script appear to be consistent with what was done for VSSPO, which *does* match between test and reference. No obvious reason for why the values for VSSPW do not. 

Refer to 2020-03-30_tc1515_M3SD.html

**Comment by TomTensfeldt** [comment]
Retested with commit c49a1b4 with tc1515_M3SD

Testcase fails.
## Scaling factor for ML/HR/LB to ML/HR/KG incorrect
unit_conversion : Unit Class 15: (Volume/Time/Body Weight) clw_col:  CLOW CLPW  parameters are scaled from  ML/HR/LB  to  ML/HR/KG  via scaling factor:  2.204624

See #217 for related issues

**Comment by jhhughes256** [comment]
This test now runs successfully with VSSO and VSSP matching reference values. @TomTensfeldt I'm not certain why conversion from ML/HR/LB to ML/HR/KG is incorrect?

LB to KG is divide by ~2.205, so wouldn't /LB to /KG be multiple by ~2.205?
