### ISSUE TITLE
2020-04-06 tc1582 M1SD CMAXDN isn't correct. CMAX not correctly dose normalized as CMAXDN.

### ISSUE THREAD

**Issue by TomTensfeldt** [tensfeldt/openNCA#224]
# Issue
Test tc1582 is an M1SD using mct$DOSE1 ("DOSE" in input concentration data) and mct$DOSE1U ("DOSEUNI" in input concentration data). In the input concentration data, the unique value of DOSEUNI is "MG".

Note that target output unit, mct$DOSEOUTPUTUNIT, is also set to "MG".

CMAX values are computed by the computation engine in the range
```r
> range(r$CMAX)
[1]  5.92 30.90
```r

CMAX values (units in UG/ML and target output units in UG/ML as well) provided by the reference results are in the range
```r
> range(refparams$CMAX1)
[1]  5.92 30.90
```
If CMAX is "dose normalized" as CMAXDN from reference results, the data are
```r
> range(refparams$CMAX1/refparams$DOSE)
[1] 0.02384 0.12360
```

However CMAXDN from the computation engine results are
```r
> range(r$CMAXDN)
[1]  23.84 123.60
``` 
indicating that NO dose normalization was completed.

Testcase data are stored in onedrive.

Refer to 2020-04-06_tc1582_M1SD.html

**Comment by jhhughes256** [comment]
As of b1c7cff this issue no longer occurs as seen in the automated testcase from 16th April.

tc1582 M1SD Execution
openNCA commit id b1c7cff

Compare CMAX parameters
```r
clist <- compare_parameters("CMAX([0-9|i|I]){0,1}$", alist=assessedparameters, ref.params=refparams, tst.params=results, tol=tolerance)
## testing CMAX1 vs CMAX 
## Equal
if(length(clist$n.ref)>0 & length(clist$n.tst)>0) assessedparameters <- remove1(assessedparameters, clist$rname)
```

Add CMAX1DN to refparams
DOSE in MG with mct$DOSEOUTPUTUNIT in MG
CONC in UG/ML with mct$CONCOUTPUTUNIT in UG/ML
```r
refparams$CMAX1DN <- refparams$CMAX1/refparams[,mct$DOSE1] 
clist <- compare_parameters("CMAX([0-9|i|I]){0,1}DN$", alist=assessedparameters, ref.params=refparams, tst.params=results, tol=tolerance)
## testing CMAX1DN vs CMAXDN 
## Equal
if(length(clist$n.ref)>0 & length(clist$n.tst)>0) assessedparameters <- remove1(assessedparameters, clist$rname)
```
