### ISSUE TITLE
2020-05-05 tc1577_M1SS fails 

### ISSUE THREAD

**Issue by TomTensfeldt** [tensfeldt/openNCA#231]
Testcase tc1577_M1SS is loaded to onedrive. The following is tested with commit b49951d.

The test case was to be used to confirm changes to the computation engine to appropriately accommodate missing data at the time of dosing for a dosing interval. 

This test case is a 2 pattern dosing interval design

Pattern 1 has 
TOLD1 TAU1 TOLD2 TAU2
0          10      10       14

Pattern 2 has
TOLD1 TAU1 TOLD2 TAU2
0          24             

where there are no values for TOLD2 and TAU2 for the second pattern.

Note that the mct$TIME was set to "NOMINAL" and AUCMETHOD to "LINLOG"

The test case was set up to run an intial execution so that no missing data occurred at time of the dosing interval. The execution of this part failed to execute providing an error message as follows:

```r
> (tclabel <- paste0("results.", testcase.id, ".", mct$MODEL, ".", mct$DOSINGTYPE, ".", mct$AUCMETHOD))
[1] "results.tc1577.M1.SS.LINLOG"
> results_list <- run_computation(data=d, map=mct, flag=flags, parameterset=parameterset)
Error in if (told < prev_tau[[j]][k]) { : 
  missing value where TRUE/FALSE needed
```

Then the 10 hour sample was removed (end of DI1 and start of DI1) for a selection of the profiles taking care to ensure that the flags dataset was aligned appropriately with the result. This also failed to execute as expected with the following error message:

```r
[1] "results.tc1577.M1.SS.LINLOG"
> results_list <- run_computation(data=d, map=mct, flag=flags, parameterset=parameterset)
Error in if (told < prev_tau[[j]][k]) { : 
  missing value where TRUE/FALSE needed
```

The testcase execution log is attached for reference. 
[tc1577_M1SS_b49951d.log](https://github.com/tensfeldt/openNCA/files/4582275/tc1577_M1SS_b49951d.log)

This testcase was to test  issues #37 and 41 from CE V2 scope.

**Comment by TomTensfeldt** [comment]
Re-executed with c57319f and runs through the run_computation including the 10 hour time point but crashes with the 10 hour time point removed for some of the SDEIDs. The log is attached here for reference and the error message is here:

```r
label: no10hr (with options)
List of 1
 $ echo: logi TRUE

Quitting from lines 363-369 (tc1577_M1SS.spin.Rmd)
Error in value[[3L]](cond) :
  Error in auc_last(conc = tmp_conc_di, time = tmp_di_df[, map_data$TIME], : Error in auc_last: length of 'time' and 'conc' vectors are not equal
For SDEID 11
Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
```

Note the inputs and outputs from this execution are updated on onedrive.

[tc1577_M1SS_c57319f-2.log](https://github.com/tensfeldt/openNCA/files/4583838/tc1577_M1SS_c57319f-2.log)

**Comment by TomTensfeldt** [comment]
Retested with commit 35c2b2b. The test case fails again with

```r
Error in value[[3L]](cond) : 

  Error in if (overall_last_time > tmp_last_time) {: argument is of length zero

For SDEID 2

Calls: <Anonymous> ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>

```

**Comment by jhhughes256** [comment]
tc1577 ran successfully with commit ed0aed3, however is now experiencing execution errors as described in #234. To avoid duplication this issue will be closed.
