### ISSUE TITLE
2020-05-11 tc1511_M1SS partial aucs incorrect

### ISSUE THREAD

**Issue by TomTensfeldt** [tensfeldt/openNCA#235]
Tested with commit b76b846

AUC0-12, AUC12-24 are incorrect and don't match AUCTAU1 (0-12), AUCTAU2 (12-24)

AUC0-48 is also at least twice the expected value.

**Comment by jhhughes256** [comment]
Linking this issue with #228

**Comment by jhhughes256** [comment]
This appears to have been addressed with commit 488fa8e according to results from the automated testing reports (thanks Chris!).
