### ISSUE TITLE
2020-07-10 tc1401 AUCTAU with a single dosing interval has incorrect values

### ISSUE THREAD

**Issue by TomTensfeldt** [tensfeldt/openNCA#253]
testcase tc1401_M1SS - executed with commit f5bfc3a

testcase Loaded to oneDrive

AUCTAU values for a single dosing interval are much larger than expected. Compare to AUC0_12 values in the table below for context.

Note also that the computation engine is not behaving as expected relative to FLGACCEPTTAU and LASTTIMEACCEPTCRIT. In the results below, LASTTIMEACCEPTCRIT is set to 0.1 (default is 0.95). If LASTTIMEACCEPTCRIT is set to the default value of 0.95, many of the AUCTAU values are not displayed. This is not consistent with the expected behavior for FLGACCEPTTAU. What should occur is that the values computed for AUCTAU would be reported regardless of the value of the FLGACCEPTTAU. FLGACCEPTTAU is set to 1 (accept) or 0 (reject) but the analyst makes the decision what to do with the actual values of AUCTAU. Additional examples illustrating this behavior can be provided.

| AUCALL | AUCLAST | AUC1 | AUC2 | AUC3 | AUC4 | AUC5 | AUC6 | AUC7 | AUC8 | AUC0_12 | AUCTAU1 | CONC1 | CONC2 | CONC3 | CONC4 | CONC5 | CONC6 | CONC7 | CONC8 | CONC9 | CONCTIME1 | CONCTIME2 | CONCTIME3 | CONCTIME4 | CONCTIME5 | CONCTIME6 | CONCTIME7 | CONCTIME8 | CONCTIME9 |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| 51.14407 | 46.88687 | 0.00000 | 0.17875 | 4.29130 | 18.33130 | 30.80946 | 38.28337 | 46.88687 | 51.14407 | 51.38527 | 78.95701 | 0.00 | 0.00 | 1.43 | 13.0 | 18.20 | 9.11 | 5.44 | 2.32 | 0.00 | 0.0 | 0.28 | 0.53 | 1.10 | 2.00 | 2.95 | 4.00 | 6.35 | 10.02 |
| 25.34162 | 22.97912 | 0.29750 | 1.94500 | 7.37000 | 12.63378 | 16.86365 | 22.97912 | 25.34162 | 25.34162 | 25.70838 | 32.53800 | 0.00 | 2.38 | 10.80 | 10.9 | 4.19 | 4.27 | 2.10 | 0.00 | 0.00 | 0.0 | 0.25 | 0.50 | 1.00 | 1.75 | 2.75 | 4.75 | 7.00 | 10.00 |
| 1447.61804 | 1447.61804 | 21.32500 | 61.70000 | 146.70000 | 383.52979 | 572.85110 | 767.32333 | 1102.27457 | 1447.61804 | 1503.14742 | 1793.59510 | 29.60 | 141.00 | 182.00 | 243.0 | 201.00 | 220.00 | 171.00 | 164.00 | 34.00 | 0.0 | 0.25 | 0.50 | 0.90 | 1.97 | 2.87 | 3.87 | 5.87 | 10.05 |
| 2617.80490 | 2617.80490 | 46.87500 | 136.33500 | 381.15000 | 727.26500 | 1158.42847 | 1430.39850 | 1907.21517 | 2617.80490 | 2870.49776 | 3111.33438 | 170.00 | 205.00 | 434.00 | 425.0 | 474.00 | 302.00 | 244.00 | 226.00 | 139.00 | 0.0 | 0.25 | 0.53 | 1.10 | 1.87 | 3.00 | 4.00 | 6.03 | 10.00 |
| 362.00181 | 362.00181 | 3.46875 | 12.96875 | 81.41675 | 161.07875 | 234.91777 | 277.23297 | 324.53684 | 362.00181 | 369.45181 | 437.40883 | 7.15 | 20.60 | 55.40 | 93.4 | 131.00 | 51.10 | 34.60 | 15.30 | 5.21 | 0.0 | 0.25 | 0.50 | 1.42 | 2.13 | 3.00 | 4.00 | 6.00 | 10.00 |
| 1909.78704 | 1909.78704 | 3.48600 | 9.09600 | 63.53000 | 235.32000 | 597.12000 | 912.47269 | 1374.58089 | 1909.78704 | 2005.99618 | 2620.05928 | 0.00 | 24.90 | 26.10 | 134.0 | 285.00 | 385.00 | 366.00 | 206.00 | 63.50 | 0.0 | 0.28 | 0.50 | 1.18 | 2.00 | 3.08 | 3.92 | 5.58 | 10.00 |
| 482.88859 | 482.88859 | 7.05000 | 24.15000 | 90.18000 | 181.83000 | 279.17996 | 332.89914 | 418.53719 | 482.88859 | 565.00613 | 695.17038 | 23.60 | 32.80 | 104.00 | 109.0 | 126.00 | 59.30 | 48.50 | 37.60 | 27.30 | 0.0 | 0.25 | 0.50 | 1.12 | 1.90 | 3.00 | 4.00 | 6.00 | 8.00 |
| 1222.87645 | 1222.87645 | 0.37145 | 4.14580 | 41.53780 | 191.49780 | 372.09780 | 569.73780 | 871.26329 | 1222.87645 | 1281.97303 | 1701.12545 | 0.00 | 3.23 | 22.80 | 133.0 | 193.00 | 151.00 | 215.00 | 150.00 | 38.70 | 0.0 | 0.23 | 0.52 | 1.00 | 1.92 | 2.97 | 4.05 | 5.72 | 10.00 |
| 434.25583 | 434.25583 | 37.97312 | 73.08611 | 135.68942 | 233.76546 | 302.50987 | 353.37939 | 434.25583 | NA | 1769.33611 | 37.97312 | 159.00 | 145.00 | 136.00 | 115.0 | 82.90 | 56.30 | 45.80 | 32.70 | NA | 11.5 | 11.75 | 12.00 | 12.50 | 13.50 | 14.50 | 15.50 | 17.58 | NA |
| 1570.79276 | 1570.79276 | 4.56250 | 12.63750 | 36.41250 | 251.16250 | 589.10468 | 861.47546 | 1330.86593 | 1570.79276 | 1636.84280 | 2543.37474 | 12.50 | 24.00 | 40.60 | 54.5 | 375.00 | 352.00 | 298.00 | 145.00 | 35.90 | 0.0 | 0.25 | 0.50 | 1.00 | 2.00 | 2.93 | 3.77 | 5.98 | 9.05 |

**Comment by jhhughes256** [comment]
This issue no longer occurs as of latest commit cca452d. Output shown below for f5bfc3a commit as well as latest.

```r
knitr::kable(data.frame(r_old$AUC0_12, r_old$AUCTAU1, r$AUC0_12, r$AUCTAU1))
```

| r_old.AUC0_12| r_old.AUCTAU1|  r.AUC0_12|   r.AUCTAU1|
|-------------:|-------------:|----------:|-----------:|
|      51.38527|     78.957010|   51.38527|   51.385272|
|      25.70838|     32.537996|   25.70838|   25.708376|
|    1503.14742|   1793.595104| 1503.14742| 1503.147419|
|    2870.49776|   3111.334381| 2870.49776| 2870.497760|
|     369.45181|    437.408828|  369.45181|  369.451808|
|    2005.99618|   2620.059278| 2005.99618| 2005.996180|
|     565.00613|    695.170380|  565.00613|  565.006131|
|    1281.97303|   1701.125455| 1281.97303| 1281.973026|
|    1769.33611|     37.973121| 1769.33611|   37.973121|
|    1636.84280|   2543.374740| 1636.84280| 1636.842802|
