### ISSUE TITLE
2020-08-31 tc1661_M1SD_cca452d DOSE unit changes from DOSEUNI=MG/KG to HR in the units conversion routine even though DOSEOUTPUTUNIT == MG/KG

### ISSUE THREAD

**Issue by TomTensfeldt** [tensfeldt/openNCA#262]
Dose unit error with dose normalized for body size (mg/kg, mg/lb, mg/m2)

Identified with tc1661_M1SD_cca452d commit cca452d

Issue: Computation engine is changing DOSE unit from DOSEUINI=MG/KG to HR in the units conversion routine even though DOSEOUTPUTUNIT is set to MG/KG

Scaling factor message:

## unit_conversion : Unit Class 3 (Dose) dose_col: DOSE parameters are scaled from MG/LB to HR via scaling factor: 1

Presumably because of this invalid unit, the dose values are being not being scaled as required for clearance/volume parameter calculations: DOSEC is identical to DOSE, and parameter results are consistent with this.

Note that parameter reporting rules for clearance and volume are being correctly applied:

· Parameters that are NOT normalized for body size are not reported

· Body size-normalized parameters are reported as expected (but the values are incorrect due to lack of scaling)

Also note there are no issues with the calculation of dose-normalized parameters since these do not require scaling.

**Comment by jhhughes256** [comment]
This issue no longer occurs as of commit 2c5406e.
