### ISSUE TITLE
2020-09-01 tc1577_M1SS-2 fails to execute with commit cca452d

### ISSUE THREAD

**Issue by TomTensfeldt** [tensfeldt/openNCA#263]
tc1577_M1SS-2 is a copy of tc1577_M1SS-1 with the 10 hour data point removed to test the effect of missing point at TOLD2.

The test case executes with commit f5bfc3a but fails to execute with commit cca452d

The error message is:
``` r
> results_list <- run_computation(data=d, map=mct, flag=flags, parameterset=parameterset)
openNCA computation engine version 3.0.0
Computation Run Date/Time: 2020-09-01 15:05:04
Error in value[[3L]](cond) : 
  Error in tlast(conc = conc, time = time): Error in tlast: length of 'time' and 'conc' vectors are not equal
For SDEID 110358863
In addition: Warning messages:
1: In run_computation(data = d, map = mct, flag = flags, parameterset = parameterset) :
  Map 'OPTMIZEKEL' does not have a valid value! Not using KEL optmization for this computation
2: In run_M1_SS_computation(data = merged_data, map = map_data, method = method,  :
  Flag 'FLGEMESIS' is not present in the dataset
3: In run_M1_SS_computation(data = merged_data, map = map_data, method = method,  :
  Map 'OPTIMIZEKEL' does not have a valid value! Not using KEL optimization for this computation

```

The message indicating that the length of time and concentraiton vectors not equal is not borne out by the data provided for execution.

All data is loaded to onedrive.

**Comment by jhhughes256** [comment]
I was able to replicate this behaviour with tc1577_M1SS-2 on commit cca452d.

With the commit 472a0a2 this error no longer occurs when run locally. There are still issues with the automated report as far as I am aware.

This testcase will still need to have its output looked at. Output for the first two profiles and warnings shown below.

|     SDEID| DOSE1| DOSE2| DOSEC| DOSEC1| DOSEC2|   C0| CMAX| CMAX1| CMAX2| CMAXC1| CMAXC2| CMAXDN| CMAXDN1| CMAXDN2| FLGACCEPTPREDOSE| CMIN| CMIN1| CMIN2| CMINDN| CMINDN1| CMINDN2| CLAST| CLAST1| CLAST2| TMAX| TMAX1| TMAX2| FLGACCEPTTMAX|     TMIN|    TMIN1| TMIN2|    TLAST|   TLAST1|   TLAST2| TLAG| CTROUGH1| CTROUGH2| CTROUGHEND1| CTROUGHEND2| PTROUGHR1| PTROUGHR2| PTROUGHREND1| PTROUGHREND2| KEL| KELC0| KELTMLO| KELTMHI| KELNOPT| KELR| KELRSQ| KELRSQA| FLGACCEPTKEL| THALF| THALFF| LASTTIME| LASTTIME1| LASTTIME2| FLGACCEPTTAU|    AUCALL| AUCALLDN1| AUCALLDN2|   AUCLAST| AUCLASTDN|  AUCLAST1| AUCLAST2| AUCLASTDN1| AUCLASTDN2|  AUMCLAST1| AUMCLAST2|   AUC1|    AUC2|     AUC3|     AUC4|     AUC5|    AUC6|     AUC7|      AUC8|      AUC9| AUC1DN| AUC2DN|   AUC3DN|   AUC4DN|   AUC5DN|   AUC6DN|   AUC7DN|    AUC8DN|   AUC9DN|AUCINT1 |AUCINT2 |AUCINT3            |AUCINT4 |AUCINT5 |AUCINT6 |AUCINT7 |AUCINT8 |AUCINT9            | AUCINFO| AUCINFO1| AUCINFO2| AUCINFOC1| AUCINFOC2| AUCINFODN| AUCINFODN1| AUCINFODN2| CEST| AUCINFP| AUCINFP1| AUCINFP2| AUCINFPC1| AUCINFPC2| AUCINFPDN| AUCINFPDN1| AUCINFPDN2| AUMCINFO1| AUMCINFO2| AUMCINFP1| AUMCINFP2|   AUCTAU1|  AUCTAU2| AUCTAUDN1| AUCTAUDN2| AUMCTAU1| AUMCTAU2|   MRTLAST|  MRTLAST1| MRTLAST2| MRTEVIFO1| MRTEVIFO2| MRTEVIFP1| MRTEVIFP2| AUCXPCTO| AUCXPCTO1| AUCXPCTO2| AUCXPCTP| AUCXPCTP1| AUCXPCTP2| AUMCXPTO1| AUMCXPTO2| AUMCXPTP1| AUMCXPTP2|     CAV1|     CAV2|   CLFTAU1| CLFTAU2|  CLFTAUW1| CLFTAUW2|      PTF1|      PTF2|     PTR1|     PTR2| VZFTAU1| VZFTAU2| VZFTAUW1| VZFTAUW2| CONC1| CONC2| CONC3| CONC4| CONC5| CONC6| CONC7| CONC8| CONC9| CONC10| CONCTIME1| CONCTIME2| CONCTIME3| CONCTIME4| CONCTIME5| CONCTIME6| CONCTIME7| CONCTIME8| CONCTIME9| CONCTIME10|DI1                |DI2                   | TAU1| TAU2| TOLD1| TOLD2| CTOLDest1| CTOLDest2|TIMEU |AMOUNTU |DOSEU |VOLUMEU |CONCU |KELU |CLU  |AUCU     |AUMCU       |AUCNORMU    |AURCU |CONCNORMU |RATEU |VOLUMEWU |CLWU    |STUDY    | SITEID|   SUBJID| RAND|TREATXT                             |TRTCD |PKCOLL |PKBDFLD |PKTERM     |PERIODU |PERIOD |VISITU | VISIT|PHASE | DOSE|  HT|    WT|AGEDERU | AGEDER|WTUNI | WTRAW|HTUNI | HTRAW|RACEOTH |RACES |SEX |RACIALD |ETHNIC |PKRCOM |PKPCOM |
|---------:|-----:|-----:|-----:|------:|------:|----:|----:|-----:|-----:|------:|------:|------:|-------:|-------:|----------------:|----:|-----:|-----:|------:|-------:|-------:|-----:|------:|------:|----:|-----:|-----:|-------------:|--------:|--------:|-----:|--------:|--------:|--------:|----:|--------:|--------:|-----------:|-----------:|---------:|---------:|------------:|------------:|---:|-----:|-------:|-------:|-------:|----:|------:|-------:|------------:|-----:|------:|--------:|---------:|---------:|------------:|---------:|---------:|---------:|---------:|---------:|---------:|--------:|----------:|----------:|----------:|---------:|------:|-------:|--------:|--------:|--------:|-------:|--------:|---------:|---------:|------:|------:|--------:|--------:|--------:|--------:|--------:|---------:|--------:|:-------|:-------|:------------------|:-------|:-------|:-------|:-------|:-------|:------------------|-------:|--------:|--------:|---------:|---------:|---------:|----------:|----------:|----:|-------:|--------:|--------:|---------:|---------:|---------:|----------:|----------:|---------:|---------:|---------:|---------:|---------:|--------:|---------:|---------:|--------:|--------:|---------:|---------:|--------:|---------:|---------:|---------:|---------:|--------:|---------:|---------:|--------:|---------:|---------:|---------:|---------:|---------:|---------:|--------:|--------:|---------:|-------:|---------:|--------:|---------:|---------:|--------:|--------:|-------:|-------:|--------:|--------:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|-----:|------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|---------:|----------:|:------------------|:---------------------|----:|----:|-----:|-----:|---------:|---------:|:-----|:-------|:-----|:-------|:-----|:----|:----|:--------|:-----------|:-----------|:-----|:---------|:-----|:--------|:-------|:--------|------:|--------:|----:|:-----------------------------------|:-----|:------|:-------|:----------|:-------|:------|:------|-----:|:-----|----:|---:|-----:|:-------|------:|:-----|-----:|:-----|-----:|:-------|:-----|:---|:-------|:------|:------|:------|
|  42088261|   0.5|    NA| 5e+05|  5e+05|  5e+05| 5.47| 8.08|  8.08|    NA|     NA|     NA|  16.16|   16.16|      NA|                0| 4.85|  4.85|    NA|   9.70|    9.70|      NA|  4.85|   4.85|     NA|    3|     3|    NA|             1| 23.91667| 23.91667|    NA| 23.91667| 23.91667|       NA|    0|     5.47|       NA|        4.85|          NA|  1.477148|        NA|     1.665979|           NA|  NA|    NA|      NA|      NA|       0|   NA|     NA|      NA|            0|    NA|     NA| 23.91667|  23.91667|        NA|            0| 154.00084|  308.0017|        NA| 154.00084|  308.0017| 154.00084|       NA|  308.00167|         NA| 1718.48565|        NA| 9.2775| 20.5125| 28.27324| 43.24313| 82.98679| 92.6747| 98.72953| 110.91951| 154.00084| 18.555| 41.025| 56.54648| 86.48626| 165.9736| 185.3494| 197.4591| 221.83902| 308.0017|0_1.5   |0_3     |0_4                |0_6     |0_11.5  |0_13    |0_14    |0_16    |0_23.9166666666667 |      NA|       NA|       NA|        NA|        NA|        NA|         NA|         NA|   NA|      NA|       NA|       NA|        NA|        NA|        NA|         NA|         NA|        NA|        NA|        NA|        NA| 154.00084|       NA| 308.00167|        NA|       NA|       NA| 11.158937| 11.158937|       NA|        NA|        NA|        NA|        NA|       NA|        NA|        NA|       NA|        NA|        NA|        NA|        NA|        NA|        NA| 6.416702|       NA|  3.246736|      NA| 0.0417366|       NA| 0.5033739|        NA| 1.665979|       NA|      NA|      NA|       NA|       NA|  5.47|  6.90|  8.08|  7.45|  7.52|  6.94|  6.00|  6.11|  6.08|   4.85|         0|       1.5|         3|  4.000000|         6|      11.5|        13|        14|        16|   23.91667|0-23.9166666666667 |NA                    |   24|   NA|     0|    NA|        NA|        NA|HR    |NA      |MG    |L       |NG/ML |1/HR |L/HR |NG.HR/ML |NG.HR.HR/ML |NG.HR/ML/MG |NA    |NG/ML/MG  |NA    |L/KG     |L/HR/KG |A3051106 |   1002| 10021013|   49|Two-Week QD Titration Scheme        |D     |POINT  |PLASMA  |CP-526,555 |NA      |NA     |DAY    |    14|NA    |  500| 160| 77.78|YR      |     78|LB    | 171.5|IN    |  63.0|NA      |W     |F   |NA      |NA     |NA     |NA     |
| 110358863|   0.5|   0.5| 5e+05|  5e+05|  5e+05| 3.28| 5.69|  5.39|  5.69|     NA|     NA|  11.38|   10.78|   11.38|                0| 3.28|  3.28|   3.5|   6.56|    6.56|       7|  3.50|   4.52|    3.5|   14|     3|    14|             1|  0.00000|  0.00000|    10| 23.96667|  6.00000| 23.96667|    0|     3.28|      3.5|        3.50|         3.5|  1.643293|  1.625714|     1.540000|     1.625714|  NA|    NA|      NA|      NA|       0|   NA|     NA|      NA|            0|    NA|     NA| 23.96667|   6.00000|  23.96667|            1|  88.67635|  177.3527|  177.3527|  88.67635|  177.3527|  26.50222| 62.17413|   53.00445|   124.3483|   85.35436|  402.9061| 5.1525| 11.8875| 17.38236| 26.50222|       NA|  7.2225| 12.52250|  23.04015|  56.00913| 10.305| 23.775| 34.76471| 53.00445|       NA|  14.4450|  25.0450|  46.08029| 112.0183|0_1.5   |0_3     |0_4.06666666666667 |0_6     |0_11.5  |0_13    |0_14    |0_16    |0_23.9666666666667 |      NA|       NA|       NA|        NA|        NA|        NA|         NA|         NA|   NA|      NA|       NA|       NA|        NA|        NA|        NA|         NA|         NA|        NA|        NA|        NA|        NA|  44.86989| 62.17413|  89.73979|  124.3483| 232.4885| 402.9061|  5.506096|  3.220649| 6.480286|        NA|        NA|        NA|        NA|       NA|        NA|        NA|       NA|        NA|        NA|        NA|        NA|        NA|        NA| 4.486989| 4.441009| 11.143329| 8.04193| 0.1516473| 0.109441| 0.4702485| 0.4931312| 1.643293| 1.625714|      NA|      NA|       NA|       NA|  3.28|  3.59|  5.39|  4.92|  4.52|  4.72|  4.91|  5.69|  4.85|   3.50|         0|       1.5|         3|  4.066667|         6|      11.5|        13|        14|        16|   23.96667|0-6                |11.5-23.9666666666667 |   10|   14|     0|    10|        NA|       3.5|HR    |NA      |MG    |L       |NG/ML |1/HR |L/HR |NG.HR/ML |NG.HR.HR/ML |NG.HR/ML/MG |NA    |NG/ML/MG  |NA    |L/KG     |L/HR/KG |A3051106 |   1001| 10011058|  112|Varenicline Weekly Titration Scheme |B     |POINT  |PLASMA  |CP-526,555 |NA      |NA     |DAY    |    14|NA    |  500| 162| 73.47|YR      |     77|LB    | 162.0|IN    |  63.9|NA      |W     |M   |NA      |NA     |NA     |NA     |

```r
Warning messages:
1: In run_computation(data = d, map = mct, flag = flags,  ... :
  Map 'OPTMIZEKEL' does not have a valid value! Not using KEL optmization for this computation
2: In run_M1_SS_computation(data = merged_data, map = map_data,  ... :
  Flag 'FLGEMESIS' is not present in the dataset
3: In run_M1_SS_computation(data = merged_data, map = map_data,  ... :
  Map 'OPTIMIZEKEL' does not have a valid value! Not using KEL optimization for this computation
4: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '110358863'
5: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '110358863'
6: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '212373988'
7: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '212373988'
8: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '483025130'
9: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '483025130'
10: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '1054705348'
11: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '1054705348'
12: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '1426390924'
13: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '1426390924'
14: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '1963203211'
15: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '1963203211'
16: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '2170425883'
17: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '2170425883'
18: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '2199664341'
19: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '2199664341'
20: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '2581673757'
21: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '2581673757'
22: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '2661584776'
23: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '2661584776'
24: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '3153628540'
25: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '3153628540'
26: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '3849379191'
27: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '3849379191'
28: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '4245137068'
29: In doTryCatch(return(expr), name, parentenv, handler) :
  Missing concentration at TAU and/or TOLD for SDEID: '4245137068'
30: In unit_conversion(data = data_data, map = map_data, result = computation_df,  ... :
  'AMOUNTU' #2# is not present in the dataset provided via 'map'
31: In unit_conversion(data = data_data, map = map_data, result = computation_df,  ... :
  'PKATPDU' and 'PKCNCU' #10# are not present in the dataset provided via 'map'
```

**Comment by jhhughes256** [comment]
The HTML report has been shown to run for this testcase. Closing.
