### ISSUE TITLE
2020-09-11 tc1704_M3SS CMIN is not included at pre-dose/zero concentration for the parameter AUCLAST

### ISSUE THREAD

**Issue by TomTensfeldt** [tensfeldt/openNCA#268]
Testcase tc1704_M3SS demonstrates with commit cca452d that CMIN is not included as specified in the value of AUCLAST generated for Model 3 Steady State.

The concentration data using actual time post dose (PKATPD) is as follows

|     SDEID| SUBJID| PKPTMS| PKATPD| PKCNCN| TOLD| TAU|
|---------:|------:|------:|------:|------:|----:|---:|
| 130080925|      1|    0.5|   0.50| 347.00|    0| 168|
| 130080925|      1|    2.0|   2.00| 109.00|    0| 168|
| 130080925|      1|    8.0|   8.00|  39.50|    0| 168|
| 130080925|      1|   24.0|  24.00|  16.00|    0| 168|
| 130080925|      1|   72.0|  70.00|   2.91|    0| 168|
| 130080925|      1|  120.0|  93.25|   1.29|    0| 168|
| 130080925|      1|  168.0| 164.25|   1.85|    0| 168|

The results from execution of run_computation are summarized as follows:

|     SDEID| CMIN|  AUCLAST| AUCLAST1|  AUCTAU1| CTOLDest1|
|---------:|----:|--------:|--------:|--------:|---------:|
| 130080925| 1.29| 1645.032| 1732.104| 1736.289|      1.29|

Note that AUCLAST and AUCLAST1 differ considerably.

The reason for this is that there is no value included at pre-dose/zero time for the AUCLAST result.

All of the information supporting this testcase is stored in the onedrive repository.

**Comment by jhhughes256** [comment]
This issue no longer occurs with commit 472a0a2. Output shown below, where AUCLAST and AUCLAST1 no longer differ. This result is also reflected in the HTML reports.

```r
knitr::kable(r[c("SDEID", "CMIN", "AUCLAST", "AUCLAST1", "AUCTAU1", "CTOLDest1")])
```

|     SDEID| CMIN|  AUCLAST| AUCLAST1|  AUCTAU1| CTOLDest1|
|---------:|----:|--------:|--------:|--------:|---------:|
| 130080925| 1.29| 1732.104| 1732.104| 1736.289|      1.29|
