### ISSUE TITLE
2019-11-08 Code Commit Fails tc010. 

### ISSUE THREAD

**Issue by tensfeldt** [tensfeldt/openNCA#3]
Something has changes drastically with out the map_data is being evaluated relative to the master branch. No change has occurred to tc010 configuration. Please execute tc010 and provide results and review and resolve ASAP.

> results_list <- run_computation(data=d, map=mct, flag=flags, parameterset=parameterset)
Error in value[[3L]](cond) : 
  Error in `[.data.frame`(map_data, , opt_list[3]): undefined columns selected
For SDEID 2925168
In addition: Warning messages:
1: In run_M1_SD_computation(data = merged_data, map = map_data, method = method,  :
  Flag 'FLGACCEPTTAU' cannot be computed if 'TAUi' is not provided
2: In run_M1_SD_computation(data = merged_data, map = map_data, method = method,  :
 
 Show Traceback
 
 Rerun with Debug
 Error in value[[3L]](cond) : 
  Error in `[.data.frame`(map_data, , opt_list[3]): undefined columns selected
For SDEID 2925168 

7.
stop(paste0(e, "For SDEID ", unique(data_data[, map_data$SDEID])[i])) at run_M1_SD_computation.R#1624
6.
value[[3L]](cond) 
5.
tryCatchOne(expr, names, parentenv, handlers[[1L]]) 
4.
tryCatchList(expr, classes, parentenv, handlers) 
3.
tryCatch({
    tmp_df <- data_data[data_data[, map_data$SDEID] == unique(data_data[, 
        map_data$SDEID])[i], ]
    tmp_df <- tmp_df[order(tmp_df[, map_data$TIME]), ] ... at run_M1_SD_computation.R#812
2.
run_M1_SD_computation(data = merged_data, map = map_data, method = method, 
    model_regex = model_regex, parameter_list = parameter_list, 
    return_list = return_list) at run_computation.R#2217
1.
run_computation(data = d, map = mct, flag = flags, parameterset = parameterset)

**Comment by jhhughes256** [comment]
### Update

This issue can no longer be replicated as of commit a06c1c7461.

**Comment by jhhughes256** [comment]
### Update

This issue still can't be replicated in b2bf9b3f3c. Closing this issue for now, this issue can be re-opened if it reappears at a later time.
