### ISSUE TITLE
2019-11-20 tc013 - DOSEUNI (Dose unit) is in "MCG" so computation engine unit_conversion.R fails with an error

### ISSUE THREAD

**Issue by tensfeldt** [tensfeldt/openNCA#45]
the UG and MCG units must be made to be synonyms of each other. This must be updated in unit_conversion.R

Also, failures for unit_conversion should not invalidate execution of the computation engine. Other parameters could be generated CMAX/TMAX for example. Make resilient to these types of errors.

**Comment by rudraya** [comment]
This issue was addressed in 02b2470, please let me know if it still occurs. Also "DPM" and "ngeq" was added to unit_conversion.R

**Comment by jhhughes256** [comment]
### Update

This issue has been fixed as of 02b2470. "DPM" and "ngeq" have been added to my testing list and I will test them when I can.
