### ISSUE TITLE
2019-11-27 tc012 M1SS - FLGACCEPTKEL provides incorrect output for select records

### ISSUE THREAD

**Issue by jhhughes256** [tensfeldt/openNCA#61]
### Issue

It appears there are still some issues with FLGACCEPTKEL assigning a 0 or 1 according to FLGACCEPTKELCRIT but not to the extent of historic issues #9 and #55. 

This issue has only been found to occur with tc012 with OPTIMIZEKEL == 1 & FLGNOCMAX == 1. It is confirmed not to occur for any other M1, M2 and M3 methods with any combination of OPTIMIZEKEL and FLGNOCMAX.

### Example

SDEID where FLGACCEPTKEL is incorrect for tc012 with OPTIMIZEKEL == 1 & FLGNOCMAX == 1.

```
       SDEID        KEL KELTMLO KELTMHI KELNOPT    KELRSQ AUCXPCTP FLGACCEPTKEL
14 361955746 0.06210606       8      12       3 0.9474643 30.54658            1
26 708723045 0.08120510      10      18       3 0.9800843 21.47417            1
31 797620983 0.09514846      16      21       3 0.9772005 20.48574            1
```

Corresponding SDEIDs when OPTIMIZEKEL == 0 with correct FLGACCEPTKEL provided below. 

```
       SDEID       KEL KELTMLO KELTMHI KELNOPT    KELRSQ  AUCXPCTP FLGACCEPTKEL
14 361955746 0.1280104      12      24       3 0.9985610  8.821899            1
26 708723045 0.1062264      12      24       3 0.9943391 14.378572            1
31 797620983 0.1059488      14      24       5 0.9922606 18.033114            1
```

### Testing Info

This issue has been tested for all test cases except M4 methods, with `OPTIMIZEKEL == 0`, `OPTIMIZEKEL == 1 & FLGNOCMAX == 1` and `OPTIMIZEKEL ==1 & FLGNOCMAX == 0` (with the exception of tc016 and tc071 where `OPTIMIZEKEL == 0` was not tested and tc014 where `OPTIMIZEKEL == 1` was not tested). 

Identification was done with the following code. If comp engine provides 0 or 1 and the answer is 0 or 1 respectively, then the sum of these two codes will equal 0 or 2 (not 1). This code captures all cases where the sum is equal to 1.

```
r[with(r, (KELRSQ >= 0.9 & KELNOPT >= 3 & AUCXPCTP <= 20) + as.numeric(FLGACCEPTKEL)) == 1, 
    c("SDEID", "KEL", "KELTMLO", "KELTMHI", "KELNOPT", "KELRSQ", "AUCXPCTP", "FLGACCEPTKEL")]
```

**Comment by rudraya** [comment]
I dont believe this is an issue as of the lastest commit, not sure if this was fixed unintentionally, but this is what I am getting: 
With the default FLGACCEPTKELCRIT: "KELRSQ>=0.9,KELNOPT>=3,AUCXPCTO<=20"
```
     SDEID         KEL    KELRSQ KELNOPT AUCXPCTO AUCXPCTP FLGACCEPTKEL
1 361955746 0.06210606 0.9474643       3 16.39478 30.54658            1
2 708723045 0.08120510 0.9800843       3 17.60464 21.47417            1
3 797620983 0.09514846 0.9772005       3 19.68340 20.48574            1
```
But if I modified FLGACCEPTKELCRIT: "KELRSQ>=0.9,KELNOPT>=3,AUCXPCTP<=20"
```
      SDEID        KEL    KELRSQ KELNOPT AUCXPCTO AUCXPCTP FLGACCEPTKEL
1 361955746 0.06210606 0.9474643       3 16.39478 30.54658            0
2 708723045 0.08120510 0.9800843       3 17.60464 21.47417            0
3 797620983 0.09514846 0.9772005       3 19.68340 20.48574            0
```
Not sure if you were looking at AUCXPCTP by default or not, but once I set it to AUCXPCTP in the FLGACCEPTKELCRIT, it is working as exepcted, please let me know if that is not the case.

**Comment by jhhughes256** [comment]
It appears that this is caused by a typo in the mct. Good catch @rudraya. Closing this issue.
