### ISSUE TITLE
2019-11-29 tc013 M2SD/tc015 M3SD missing CMIN/TMIN parameter

### ISSUE THREAD

**Issue by tensfeldt** [tensfeldt/openNCA#68]
With commit 22d43ea but likely not specific to this commit, CMIN is defined in create_dependency_list for M2  and M3 (and is specified as a parameter in the Computation Engine Specification Document) but doesn't appear in 
run_M2_SD_computation.R nor run_M3_SD_computation.R and isn't created in output for these models.

**Comment by rudraya** [comment]
This issue was addressed in 6e99fab, please let me know if it still occurs.

**Comment by tensfeldt** [comment]
This was tested successfully with commit b8deb76 and can be closed.
