### ISSUE TITLE
2019-12-03 Column alignment required to run tc008 M1SD, M1SS, M4SDSS 

### ISSUE THREAD

**Issue by jhhughes256** [tensfeldt/openNCA#77]
### Testcase Issue

This data files on the OneDrive for this test case as of today has misaligned data for the first 7 columns due to a comma in the values given for TREATXT. This provides an additional column, resulting in the first column becoming the rownames for the data.frame.

The value for TREATXT in the .csv is `PF-06700841 100 mg (PO, QD)`. As this isn't in quotations this is read as two columns of values instead of one.

This can be seen below where the values for PKDATAROWID are assigned to the rownames of conc.

```
conc[1:7]
         PKDATAROWID    SDEID STUDY   SITEID SUBJID                   RAND TREATXT
66607588   363476907 B7931009  1001 10011001      1 PF-06700841 100 mg (PO     QD)
66607590   754426795 B7931009  1001 10011002      2 PF-06700841 100 mg (PO     QD)
66607594   926177600 B7931009  1001 10011004      4 PF-06700841 100 mg (PO     QD)
66607596   927450954 B7931009  1001 10011005      5 PF-06700841 100 mg (PO     QD)
66607600   225930823 B7931009  1001 10011007      7 PF-06700841 100 mg (PO     QD)
66607602   532644281 B7931009  1001 10011008      8 PF-06700841 100 mg (PO     QD)
```

The values given to the rownames are actually the PKDATAROWID as can be seen when observing the `flags` data.

```
> flags[1]
  PKDATAROWID
1    66607600
2    66607588
3    66607596
4    66607590
5    66607594
6    66607602
```

This is the full extent of the misalignment, with columns returning to normal from TRTCD onwards

```
> conc[8:20]
         TRTCD   PKCOLL PKBDFLD      PKTERM PERIODU PERIOD VISITU VISIT PHASE    PKACES PKSCOM   PKUSMID PKSAMQA
66607588     A INTERVAL   URINE PF-06700841  PERIOD      1    DAY    10    NA E.00G01D1     NA E.00G01D1   FINAL
66607590     A INTERVAL   URINE PF-06700841  PERIOD      1    DAY    10    NA E.00G02X1     NA E.00G02X1   FINAL
66607594     A INTERVAL   URINE PF-06700841  PERIOD      1    DAY    10    NA E.00G0611     NA E.00G0611   FINAL
66607596     A INTERVAL   URINE PF-06700841  PERIOD      1    DAY    10    NA E.00G07L1     NA E.00G07L1   FINAL
66607600     A INTERVAL   URINE PF-06700841  PERIOD      1    DAY    10    NA E.00G0AP1     NA E.00G0AP1   FINAL
66607602     A INTERVAL   URINE PF-06700841  PERIOD      1    DAY    10    NA E.00G15X1     NA E.00G15X1   FINAL
```

### Temporary Fix

To fix this I have been using the following code in my testing wrapper for tc008 M4SDSS. Note that this has to be done **before** `d` is defined.

```
# Fix PKDATAROWID for tc008_M4SDSS
if (p == "testcase/tc008_M4SDSS_B7931009") {
  conc$TREATXT <- paste(conc$RAND, conc$TREATXT, sep = ",")
  conc$RAND <- conc$SUBJID
  conc$SUBJID <- conc$SITEID
  conc$SITEID <- conc$STUDY
  conc$STUDY <- conc$SDEID
  conc$SDEID <- conc$PKDATAROWID
  conc$PKDATAROWID <- rownames(conc)
}
```

This gives the following values for the first 7 columns.

```
> conc[1:7]
         PKDATAROWID     SDEID    STUDY SITEID   SUBJID RAND                      TREATXT
66607588    66607588 363476907 B7931009   1001 10011001    1 PF-06700841 100 mg (PO, QD)
66607590    66607590 754426795 B7931009   1001 10011002    2 PF-06700841 100 mg (PO, QD)
66607594    66607594 926177600 B7931009   1001 10011004    4 PF-06700841 100 mg (PO, QD)
66607596    66607596 927450954 B7931009   1001 10011005    5 PF-06700841 100 mg (PO, QD)
66607600    66607600 225930823 B7931009   1001 10011007    7 PF-06700841 100 mg (PO, QD)
66607602    66607602 532644281 B7931009   1001 10011008    8 PF-06700841 100 mg (PO, QD)
```

This fix should help with the replication of #67.

**Comment by jhhughes256** [comment]
### Update

An additional change is required to run tc008 M1SS. The values for `mct$TAU1` and mct$TOLD1` are currently "TAU1" and "TOLD1" respectively. These columns do not exist in the dataset. I have changed these to "TAU" and "TOLD" respectively to run the test case.

**Comment by jhhughes256** [comment]
### Update

I noticed the changes to tc008 on the OneDrive. As the file is defined right now `B7931009.in.csv` is not correct. Only the first 7 columns are misaligned, rather than all of the columns being misaligned. 

Unfortunately I don't have permissions to upload an updated .csv to the OneDrive, so will leave this issue open until an updated dataset is provided.

**Comment by tensfeldt** [comment]
The files for tc008 M1SD, M1SS, M4SD on the sharepoint/onedrive volume have been updated to fix the issues with unquoted fields with commas embedded. This is can be closed now

**Comment by jhhughes256** [comment]
#60, #67 and #81 can now be tested using onedrive data.
