### ISSUE TITLE
AUC must evaluate to ZERO if all concentration values in profile (or selected from profile) are ZERO

### ISSUE THREAD

**Issue by tensfeldt** [tensfeldt/openNCA#83]
Think this is covered in the computation engine specification document but will confirm.

**Comment by rudraya** [comment]
Few things I noticed when attempting to resolve this issue:
- As of the commit on 12/6, only AUCLAST, AUCT and AUCT1_T2 are the ones that are resulting to 0 and are instead resulting to NA
- AUCLAST logic is working as following:
   -  Checks if all of TIME and CONC are NA or checks if length of TIME and CONC is 0, if so then returns NA
   - Checks if TLAST is NA, if so then returns NA
   - Checks if all of CONC are 0, if so then returns 0 
- AUCT and AUCT1_T2 logic is working as following: (order matters)
   - Checks if all of TIME and CONC are NA, if so then returns NA
   - Checks if TMAX is NA given that AUCMETHOD is LINLOG, if so then returns NA
   - Checks if either T1 or T2 is NA or NULL, if so then returns NA
   - Checks if T1 is less than the Dose time, if so then returns NA
   - Checks if all of CONC are 0, if so then returns 0 
Please let me know if the check for the 0s should occur prior to the previous checks mentioned above. Also please let me know if there are any other parameters besides the ones I mentioned. Based on the response to this comment, I will address and fix the issue.

**Comment by tensfeldt** [comment]
The order of the checks as described appears appropriate for AUCLAST, AUCT, AUCT1_T2.

**Comment by jhhughes256** [comment]
Since TMAX, CMAX, CLAST return NA if all concentrations are zero, then any AUC related to these parameters would return NA correct? Are all the AUCs working as intended then? Should we close this @tensfeldt?

**Comment by tensfeldt** [comment]
The check if all of TIME and CONC are NA, returning NA for AUC type parameters should occur first
The checks for CONC all zero should occur NEXT, i.e. PRIOR to the checks mentioned for TMAX, T1, T2.

**Comment by rudraya** [comment]
This issue was addressed in 1893609, please let me know if it still occurs. I changed the order of the logic as specified in the comments above.

**Comment by tensfeldt** [comment]
The decision to close this is predicated on @rudraya understanding that the issue has been addressed. Since there was not a specific test case associated with this particular issue, testing results will be inspected to ensure that this issue has resolved completely. If not it will be reopened as necessary.
