### ISSUE TITLE
2019-12-06 Steady State Models M1SS, M2SS, M3SS must not require parameter computation for KEL related parameters

### ISSUE THREAD

**Issue by tensfeldt** [tensfeldt/openNCA#92]
Testing with M1SS, M2SS and M3SS (linked with Issues #86, #88, #89, #90, #91) indicates that the steady state models require KEL parameter and KEL FLags selections. This must be relaxed.

**Comment by rudraya** [comment]
All of the issues mentioned above have been closed, so please let know what action is needed to resolve this issue, Please provide an example of where SS models require KEL to be there because as of now this doesn't seem to be occurring as frequently as it did previously.

**Comment by tensfeldt** [comment]
Currently cannot directly confirm that issue is completely addressed. Will retest with blocking issues from development milestone 1 for 2.0.1 application evaluation  and reopen as needed.
